name: Publish Python 🐍 distribution 📦 to TestPyPI

on:
  push:
    branches-ignore:
      - master

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distribution 📦 to TestPyPI
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Rust project
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install latest stable
          uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              override: true
              components: cross

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Build gateway-mfr-rs
      run: >-
        git clone https://github.com/helium/gateway-mfr-rs.git &&
        cross build --target aarch64-unknown-linux-musl --release


    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    #- name: Publish distribution 📦 to Test PyPI
    #  uses: pypa/gh-action-pypi-publish@master
    #  with:
    #    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #    repository_url: https://test.pypi.org/legacy/
