name: Publish Python 🐍 distribution 📦 to TestPyPI

on:
  push:
    branches-ignore:
      - master

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        continue-on-error: true  # WARNING: only for this example, remove it!
        with:
          command: check

      - name: Clone repo
        run: >-
          git clone https://github.com/helium/gateway-mfr-rs.git && \
          cd gateway-mfr-rs && \
          git checkout v0.1.3

      - name: Build gateway-mfr-rs
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-musl --release

  build-n-publish:
    name: Build and publish Python 🐍 distribution 📦 to TestPyPI
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    #- name: Publish distribution 📦 to Test PyPI
    #  uses: pypa/gh-action-pypi-publish@master
    #  with:
    #    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #    repository_url: https://test.pypi.org/legacy/
