name: Test

on:
  workflow_dispatch:

jobs:
  rust-compile:
    name: Build gateway-mfr-rs
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo "testing" > test.txt
          echo "test" > testing.txt
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.txt
          tag: v0.8.9
          overwrite: true
          file_glob: true
